# Generated by Django 4.2.6 on 2023-11-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='name',
            new_name='username',
        ),
    ]
